services:
  postgres:
    image: postgres:17-alpine
    container_name: asclepius-postgres
    environment:
      POSTGRES_DB: asclepius
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - asclepius-postgres:/var/lib/postgresql/data

volumes:
  asclepius-postgres:
